### PR TITLE
Update help text for docker image use (post mark of image public)

### LINKED ISSUE #110: Stored Docker Image
I've started using github-action-markdown-link-check for a personal site and noticed the majority of time executing is while building the docker image.

Would it be feasible to implement an image build that's stored in Github Packages on merge? I realize it isn't directly related to the project, but a fix would trickle downstream. @gaurav-nelson would probably have an opinion too.

Happy to submit a pull request if it's something that interests folks.

### PR DESCRIPTION
**Pull request by cadeef**
fixes #110
should gate until #112 merged

### CODE REVIEW

**Comment by NicolasMassart** [comment]
@cadeef I this ready for review/merge in you opinion?

**Comment by cadeef** [comment]
On mobile and can't see whether the docket image has been marked public. If it has, the PR is ready to merge.

**Comment by NicolasMassart** [comment]
I'm not sure if there's anything published of it's not public yet looking at https://github.com/tcort?tab=packages&repo_name=markdown-link-check
@tcort any news on this please?

**Comment by NicolasMassart** [comment]
Given [the message on merge in the #131](https://github.com/tcort/markdown-link-check/commit/4dd6ee956124558280b253dd8f2af543c0afb2d0#commitcomment-44116665), I confirm that docker image is published but not public

**Comment by cadeef** [comment]
Took a quick look to verify. Once the image is marked public, it should appear at https://github.com/users/tcort/packages/container/package/markdown-link-check .

@tcort Instructions for marking a package public can be found [here](https://docs.github.com/en/free-pro-team@latest/packages/managing-container-images-with-github-container-registry/configuring-access-control-and-visibility-for-container-images#configuring-visibility-of-container-images-for-your-personal-account), so you don't have to find the docs.

**Comment by tcort** [comment]
I've marked the image public

**Pull request merged**
