### PR TITLE
feat: Add ignoreUrls option

### PR DESCRIPTION
**Pull request by nschonni**
Completely eyeballed and not tested/run. I just wanted to through this up for discussion since I noticed you added the concept of a config file.

### CODE REVIEW

**Comment by timmkrause** [comment]
Cool! Was thinking to add this as well. Can you write a test for it?

**Comment by timmkrause** [comment]
The following came additionally came to my mind: Maybe it would make sense to rename "ignoreUrls" to "ignorePatterns" (or something) and make it regular expressions? I also have the requirement to ignore some relative markdown links. That way it would be more flexible. What do you think?

**Comment by timmkrause** [comment]
> The other part I was thinking of is if the skipped links should show up in the UI somehow. Maybe a yellow [?] instead of the check/X for the pass/failed links

Good one. Personally I would prefer that the ignore check happens within `link-check` and return an appropriate result of `ignored` so that the evaluation (and display) can be done in a consistent way by resolving the status appropriately via `statusLabels[result.status]` in `markdown-link-check.runMarkdownLinkCheck()`.

**Comment by nschonni** [comment]
Closing this in favour of #41 since it is more fleshed out, and the regex method is a better way to go

**Pull request closed without merging**
