### PR TITLE
feat: support multi inputs

### LINKED ISSUE #78: Allow specifying multiple files on the command line
This is similar to https://github.com/tcort/markdown-link-check/issues/40 but slightly different. I'd like to be able to pass multiple file names on the command line and check each one in sequence, e.g. `markdown-link-check file1.md file2.md` The motivation for this is trying to add a hook with pre-commit (https://pre-commit.com/); this splits the full list of files to check into smaller lists, but currently only one file from each list is checked.

This would also potentially allow some optimizations; for example if a URL appears in two markdown files, you would only need to make the request once and cache the status for subsequent checks.

### PR DESCRIPTION
**Pull request by kenji-miyake**
Resolves #78

This is an improved version of #178.
Although the diff is large, since I split commits into small units, I suppose you can understand what I changed by seeing each commit.

### How to test

```sh-session
$ git clone git@github.com:kenji-miyake/markdown-link-check.git -b support-multi-inputs
$ cd markdown-link-check
$ git cherry-pick 7b3ad2c1ce5e49d03ff29cbebd6951006b0ccf4a
$ # pre-commit
$ pre-commit clean
$ pre-commit run -a
[WARNING] The 'rev' field of repo '.' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[INFO] Initializing environment for ..
[INFO] Installing environment for ..
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Markdown Link Check......................................................Failed
- hook id: markdown-link-check
- exit code: 1


FILE: test-2.md

  1 links checked.

FILE: test-1.md

  1 links checked.

FILE: test-3.md
  [✖] http://common-invalid-link.example.com
  [✖] http://invalid-link3.example.com

  3 links checked.

  ERROR: 2 dead links found!
  [✖] http://common-invalid-link.example.com → Status: 0
  [✖] http://invalid-link3.example.com → Status: 0

FILE: test-4.md

  1 links checked.

$ # CLI
$ sudo npm install -g .
$ markdown-link-check test-1.md test-2.md test-3.md test-4.md

FILE: test-1.md
  [✓] http://google.com

  1 links checked.

FILE: test-2.md
  [✓] http://google.com

  1 links checked.

FILE: test-3.md
  [✓] http://google.com
  [✖] http://common-invalid-link.example.com
  [✖] http://invalid-link3.example.com

  3 links checked.

  ERROR: 2 dead links found!
  [✖] http://common-invalid-link.example.com → Status: 0
  [✖] http://invalid-link3.example.com → Status: 0

FILE: test-4.md
  [✓] http://google.com

  1 links checked.
```

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@tcort Hello, thank you for this useful tool!
Could you take a look at this, please? :pray:

**Comment by kenji-miyake** [comment]
@tcort Hi, I know you are busy, but let me friendly ping.

**Comment by kenji-miyake** [comment]
@tcort Thank you so much! :smile:

**Comment by waylan** [comment]
Shouldn't the documentation be updated to reflect this change (and demonstrate how to call with multiple files)?

https://github.com/tcort/markdown-link-check/blob/458cefb23246668dee9e65502c69fa3371b014ab/README.md?plain=1#L144-L153

**Comment by matschaffer** [comment]
I had the same question as @waylan - is there a way to enable recursive check using a cli arg? I'm using the docker command to try this out for starters. `--help` on that doesn't seem to list any "recursive" option.

**Pull request merged**
