### PR TITLE
Timeout Option added

### LINKED ISSUE #124: Timeout option
Some of websites are very slow. Is there an option to set timeout? [link-check](https://www.npmjs.com/package/link-check) has it.

### PR DESCRIPTION
**Pull request by hmert**
fixes #124

### CODE REVIEW

**Comment by NicolasMassart** [comment]
@tcort do you know what fails on the "Docker / Build & Publish (pull_request)" job?

**Comment by hmert** [comment]
the error was `Unable to find the password. Did you set with.password?`

**Comment by NicolasMassart** [comment]
Yes but what's the cause as other PR are working...

**Comment by NicolasMassart** [comment]
I think I found the issue. You created your PR before the Docker workflow was added. So you don't have the config files in it. But Github still waits for the workflow to complete.
Can you please update your fork branch by merging the upstream master in it?

**Comment by NicolasMassart** [comment]
I merged it anyway crossing my finger that it was just an issue with your PR and that it will work on master... and it did...

**Comment by hmert** [comment]
Thank you! We used your action on https://github.com/academic/awesome-datascience and it helps a lot!

**Pull request merged**
