### PR TITLE
Support URL specific headers to enable authorized requests

### PR DESCRIPTION
**Pull request by timmkrause**
Hi,

First: Thank you for your effort!

I really hope you like the changes, it works perfectly for us. Just tell me if there is something wrong from your point of view.

To get a little logging regarding which headers are supplied to certain links add the following lines in `index.js` after line #42:

```
if (!_.isEmpty(opts.headers)) {
    console.log("Checking " + link + " with headers " + JSON.stringify(opts.headers) + "");
}
```

### CODE REVIEW

**Comment by tcort** [comment]
Looking pretty good. I'll merge it later this week and I'll make a few tweaks (e.g. to handle an error that could occur if the config file contents is not valid JSON, and a few other things).

**Comment by timmkrause** [comment]
>Looking pretty good. I'll merge it later this week and I'll make a few tweaks (e.g. to handle an error that could occur if the config file contents is not valid JSON, and a few other things).

@tcort Great, sounds good. Pleased let me know if I can support you with anything. Was also thinking to cache the computed headers for certain URLs and not always recompute them. I have also seen one of your ideas regarding this feature in one of the issues. Unfortunately this happened afterwards and would lead into a different direction...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timmkrause** [comment]
@tcort I guess you still want to make the changes you just mentioned, right? Can you give me a rough estimate when the changes may get released?

**Comment by tcort** [comment]
Sorry, I've been swamped. I've released `v3.4.0` with this feature.

**Pull request merged**
